### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by MengTo** [MengTo/DesignerNewsApp#107]
I am not sure if it's just me, but it seems that the login doesn't work anymore.

**Comment by schneiderandre** [comment]
Since LayerVault has shut down, the log in isn't working anymore.
The resource we used for login under https://api-news.layervault.com/oauth/token moved permanently.

I got the login working under the host https://www.designernews.co

I'll check out if all other resources are still working with the V1 version, or if we must use the V2 instead.

**Comment by schneiderandre** [comment]
The API documentation under http://developers.news.layervault.com/v2.html is offline.
We can still find it here: https://github.com/metalabdesign/dn_api_v2
